version: '3'
services:
  ff_network:
    build: mgr/infrastructure/models/deep/feed_forward
    ports:
    - "8501:8501"
    restart: on-failure
  lstm_network:
    build: mgr/infrastructure/models/deep/lstm
    ports:
    - "8502:8501"
    restart: on-failure
  vggish:
    build: mgr/infrastructure/audioset/vggish
    ports:
    - "8503:8501"
    restart: on-failure
  server:
    build: .
    ports:
    - "5000:80"
    depends_on:
      - ff_network
      - lstm_network
      - vggish
    environment:
     - PROXIES=
    restart: on-failure
