
name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - uses: dschep/install-pipenv-action@v1
    - name: Install deps
      run: pipenv install --dev --system
    - name: Run tests
      run: pipenv run test-ci
