
name: CI worflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
    - uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: pipenv install --system
    - name: Run tests
      run: pipenv run test-ci
