
name: CI worflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      uses: dschep/install-pipenv-action@v1
      run: pipenv run test-ci
